In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%precision 3
%matplotlib inline

In [2]:
#データCSVの読み込み
df = pd.read_csv('./data/ch4_scores400.csv')
scores = np.array(df['点数'])
scores[:10]

array([76, 55, 80, 80, 74, 61, 81, 76, 23, 80])

In [3]:
#無作為抽出
np.random.choice([1, 2, 3], 3)

array([2, 3, 3])

In [4]:
#非復元抽出(復元抽出)
np.random.choice([1, 2, 3], 3, replace=False)

array([3, 2, 1])

In [5]:
#乱数シード(これから発生させる乱数の元となる数字を設定する)
np.random.seed(0)
np.random.choice([1, 2, 3], 3)

array([1, 2, 1])

In [7]:
#Aさんの行った無作為抽出はnp.random.seed(0)で乱数シードを0に指定した後に、scoresから
#サンプルサイズを20で復元抽出することで再現することができる。
#無作為抽出を行い、標本平均を計算する
np.random.seed(0)
sample = np.random.choice(scores, 20)
sample.mean()

70.4

In [8]:
#全生徒のデータから、Aさんが推測したい母平均も計算できる
scores.mean()

69.53

In [9]:
#無作為抽出は行うたびに結果が異なるため、得られる標本平均も毎回異なる。無作為抽出とその標本平均の計算を何回か行ってみる
for i in range(7):
    sample = np.random.choice(scores, 20)
    print(f'{i+1}回目の無作為抽出で得た標本平均', sample.mean())

1回目の無作為抽出で得た標本平均 72.45
2回目の無作為抽出で得た標本平均 63.7
3回目の無作為抽出で得た標本平均 66.05
4回目の無作為抽出で得た標本平均 71.7
5回目の無作為抽出で得た標本平均 74.15
6回目の無作為抽出で得た標本平均 70.7
7回目の無作為抽出で得た標本平均 71.9
